// Copies the six interface ABIs from the contracts build output into src/abi,
// and the Sepolia deployment file into src/config/deployments.json.
// Usage: npm run sync:abi
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const web = path.resolve(here, "..");
const contracts = path.resolve(web, "..", "contracts");

const NAMES = ["IThalerToken", "ICharterNFT", "ICentralBank", "IFlowHook", "ITreasury", "IThalerRouter"];
const abiDir = path.join(web, "src", "abi");
mkdirSync(abiDir, { recursive: true });

let indexTs = "// Generated by scripts/sync-abi.mjs. Do not edit by hand.\n// Typed `as const` copies of the interface ABIs so wagmi/viem can infer function names and return types.\n\n";
for (const name of NAMES) {
  const src = path.join(contracts, "out", `${name}.sol`, `${name}.json`);
  if (!existsSync(src)) {
    console.error(`missing ${src}: run \`forge build\` in contracts/ first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(src, "utf8"));
  writeFileSync(path.join(abiDir, `${name}.json`), JSON.stringify(abi, null, 2) + "\n");
  const exportName = name.replace(/^I/, "").replace(/^./, (c) => c.toLowerCase()) + "Abi";
  indexTs += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
  console.log(`abi  ${name}: ${abi.length} entries`);
}
writeFileSync(path.join(abiDir, "index.ts"), indexTs);

const ZERO = "0x0000000000000000000000000000000000000000";
const placeholder = {
  token: ZERO,
  charter: ZERO,
  centralBank: ZERO,
  treasury: ZERO,
  hook: ZERO,
  router: ZERO,
  poolManager: ZERO,
  poolId: "0x0000000000000000000000000000000000000000000000000000000000000000",
  chainId: 11155111,
  block: 0,
  deployer: ZERO,
  genesis: 0,
};

const depSrc = path.join(contracts, "deployments", "11155111.json");
const depDst = path.join(web, "src", "config", "deployments.json");
mkdirSync(path.dirname(depDst), { recursive: true });
if (existsSync(depSrc)) {
  const raw = JSON.parse(readFileSync(depSrc, "utf8"));
  const merged = { ...placeholder, ...raw };
  writeFileSync(depDst, JSON.stringify(merged, null, 2) + "\n");
  console.log(`deployments: copied from ${depSrc}`);
} else if (!existsSync(depDst)) {
  writeFileSync(depDst, JSON.stringify(placeholder, null, 2) + "\n");
  console.log(`deployments: ${depSrc} not found, wrote zero-address placeholder`);
} else {
  console.log(`deployments: ${depSrc} not found, kept existing ${depDst}`);
}
